# Shaders compiled at build time, and small files built into a binary.
#
#   kin_compile_glsl(<out_var> OUTPUT_DIR <dir> SOURCES <a.frag.glsl> ...)
#     Compiles each GLSL source to <dir>/<name>.spv with glslc, the stage taken
#     from the name (.vert, .frag or .comp before .glsl), and sets <out_var> to
#     the .spv files. With KIN_SPIRV_DIR it copies <name>.spv from there
#     instead (made by cmake/kin_spirv.cmake where glslc runs), for build
#     machines without glslc. With neither, it skips the shaders and <out_var>
#     lists only those it has.
#
#   kin_embed_files(<target> NAME <function> [NAMESPACE <ns>] FILES <file> ...)
#     Builds the files into <target>, readable by file name through
#       #include "<function>.hpp"
#       std::span<const unsigned char> <ns>::<function>(std::string_view file_name);
#       std::span<const std::string_view> <ns>::<function>_files();
#     The span is empty for a name not built in. For files of a few hundred KB
#     at most (shaders, small tables); a game's content goes in its pack.

find_program(KIN_GLSLC NAMES glslc HINTS "$ENV{VULKAN_SDK}/bin" "$ENV{VULKAN_SDK}/Bin")
set(KIN_SPIRV_DIR "" CACHE PATH "Already-compiled .spv files to use instead of glslc (cmake/kin_spirv.cmake makes them)")

set(_KIN_EMBED_GENERATOR "${CMAKE_CURRENT_LIST_DIR}/kin_embed_generate.cmake")

function(kin_compile_glsl out_var)
    cmake_parse_arguments(ARG "" "OUTPUT_DIR" "SOURCES" ${ARGN})
    set(outputs)
    if(KIN_SPIRV_DIR)
        file(MAKE_DIRECTORY "${ARG_OUTPUT_DIR}")
        foreach(source IN LISTS ARG_SOURCES)
            get_filename_component(name "${source}" NAME)
            string(REGEX REPLACE "\\.glsl$" ".spv" spv_name "${name}")
            set(prebuilt "${KIN_SPIRV_DIR}/${spv_name}")
            if(NOT EXISTS "${prebuilt}")
                message(WARNING "kin_compile_glsl: ${spv_name} is not in KIN_SPIRV_DIR (${KIN_SPIRV_DIR})")
                continue()
            endif()
            set(output "${ARG_OUTPUT_DIR}/${spv_name}")
            add_custom_command(
                OUTPUT "${output}"
                COMMAND "${CMAKE_COMMAND}" -E copy "${prebuilt}" "${output}"
                DEPENDS "${prebuilt}"
                COMMENT "SPIR-V: ${spv_name} from KIN_SPIRV_DIR"
                VERBATIM)
            list(APPEND outputs "${output}")
        endforeach()
    elseif(KIN_GLSLC)
        file(MAKE_DIRECTORY "${ARG_OUTPUT_DIR}")
        foreach(source IN LISTS ARG_SOURCES)
            get_filename_component(source "${source}" ABSOLUTE)
            get_filename_component(name "${source}" NAME)
            if(name MATCHES "\\.vert\\.glsl$")
                set(stage vertex)
            elseif(name MATCHES "\\.frag\\.glsl$")
                set(stage fragment)
            elseif(name MATCHES "\\.comp\\.glsl$")
                set(stage compute)
            else()
                message(FATAL_ERROR "kin_compile_glsl: ${name} is not .vert.glsl, .frag.glsl or .comp.glsl")
            endif()
            string(REGEX REPLACE "\\.glsl$" ".spv" spv_name "${name}")
            set(output "${ARG_OUTPUT_DIR}/${spv_name}")
            add_custom_command(
                OUTPUT "${output}"
                COMMAND "${KIN_GLSLC}" -fshader-stage=${stage} -o "${output}" "${source}"
                DEPENDS "${source}"
                COMMENT "glslc: ${name} -> ${spv_name}"
                VERBATIM)
            list(APPEND outputs "${output}")
        endforeach()
    endif()
    set(${out_var} "${outputs}" PARENT_SCOPE)
endfunction()

function(kin_embed_files target)
    cmake_parse_arguments(ARG "" "NAME;NAMESPACE" "FILES" ${ARGN})
    if(NOT ARG_NAME)
        message(FATAL_ERROR "kin_embed_files: NAME is required")
    endif()
    set(dir "${CMAKE_CURRENT_BINARY_DIR}/kin_embed/${target}")
    set(header "${dir}/${ARG_NAME}.hpp")
    set(source "${dir}/${ARG_NAME}.cpp")
    set(open_ns "")
    set(close_ns "")
    if(ARG_NAMESPACE)
        set(open_ns "namespace ${ARG_NAMESPACE} {\n\n")
        set(close_ns "\n} // namespace ${ARG_NAMESPACE}\n")
    endif()
    file(CONFIGURE OUTPUT "${header}" CONTENT
"// Generated by kin_embed_files; do not edit.
#pragma once

#include <span>
#include <string_view>

${open_ns}// A built-in file's bytes by name; empty if there is no such file.
std::span<const unsigned char> ${ARG_NAME}(std::string_view file_name);
// The names of the built-in files, sorted.
std::span<const std::string_view> ${ARG_NAME}_files();
${close_ns}")
    string(REPLACE ";" "|" files_arg "${ARG_FILES}")
    add_custom_command(
        OUTPUT "${source}"
        COMMAND "${CMAKE_COMMAND}" "-DOUTPUT=${source}" "-DHEADER=${ARG_NAME}.hpp" "-DNAME=${ARG_NAME}"
                "-DNAMESPACE=${ARG_NAMESPACE}" "-DFILES=${files_arg}" -P "${_KIN_EMBED_GENERATOR}"
        DEPENDS ${ARG_FILES} "${_KIN_EMBED_GENERATOR}"
        COMMENT "Embedding ${ARG_NAME} in ${target}"
        VERBATIM)
    target_sources(${target} PRIVATE "${source}")
    target_include_directories(${target} PRIVATE "${dir}")
endfunction()
