# cmake -DOUTPUT=<cpp> -DHEADER=<hpp> -DNAME=<function> [-DNAMESPACE=<ns>] -DFILES=<a|b|...> -P kin_embed_generate.cmake
# Writes the source that kin_embed_files builds into a target.

string(REPLACE "|" ";" files "${FILES}")

set(entries)
foreach(file IN LISTS files)
    get_filename_component(name "${file}" NAME)
    list(APPEND entries "${name}|${file}")
endforeach()
list(SORT entries)

set(arrays "")
set(table "")
set(names "")
set(index 0)
foreach(entry IN LISTS entries)
    string(REPLACE "|" ";" parts "${entry}")
    list(GET parts 0 name)
    list(GET parts 1 file)
    file(READ "${file}" hex HEX)
    string(LENGTH "${hex}" hex_length)
    math(EXPR size "${hex_length} / 2")
    # 32 bytes a line.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "((0x..,){32})" "\\1\n    " bytes "${bytes}")
    if(size EQUAL 0)
        set(bytes "0")
    endif()
    string(APPEND arrays "alignas(4) const unsigned char file_${index}[] = {\n    ${bytes}\n};\n")
    string(APPEND table "    {\"${name}\", {file_${index}, ${size}}},\n")
    string(APPEND names "    \"${name}\",\n")
    math(EXPR index "${index} + 1")
endforeach()

set(open_ns "")
set(close_ns "")
if(NAMESPACE)
    set(open_ns "namespace ${NAMESPACE} {\n\n")
    set(close_ns "\n} // namespace ${NAMESPACE}\n")
endif()

if(index EQUAL 0)
    set(body
"std::span<const unsigned char> ${NAME}(std::string_view) {
    return {};
}

std::span<const std::string_view> ${NAME}_files() {
    return {};
}
")
else()
    set(body
"namespace {

${arrays}
struct File {
    std::string_view name;
    std::span<const unsigned char> bytes;
};

constexpr File files[] = {
${table}};

constexpr std::string_view names[] = {
${names}};

} // namespace

std::span<const unsigned char> ${NAME}(std::string_view file_name) {
    const auto found = std::ranges::lower_bound(files, file_name, {}, &File::name);
    return found != std::end(files) && found->name == file_name ? found->bytes : std::span<const unsigned char>{};
}

std::span<const std::string_view> ${NAME}_files() {
    return names;
}
")
endif()

set(content
"// Generated by kin_embed_files; do not edit.
#include \"${HEADER}\"

#include <algorithm>
#include <iterator>

${open_ns}${body}${close_ns}")

file(WRITE "${OUTPUT}" "${content}")
