# Games built with kin, from their content to a package (docs/shipping.md).
#
#   kin_game(<target>
#       [CONTENT <dir>]        # the game's content folder (default: content/ beside the CMakeLists)
#       [NAME <name>]          # its name beside the executable: <name>.kinpak or <name>/ (default: <target>)
#       [TITLE <text>]         # the product name in the Windows version info (default: <name>)
#       [VERSION <x.y.z>]      # (default: the project's version)
#       [ICON <file.ico>]      # the Windows executable's icon
#       [FILES <file> ...]     # more files to ship beside the executable (a readme, ...)
#       [NO_CONTENT])          # the game has no content folder
#
# On the target it sets KIN_GAME_CONTENT_NAME and, outside shipping builds,
# KIN_GAME_CONTENT_DIR, so the game finds its content with
#   kin::find_content_root(KIN_GAME_CONTENT, argc, argv)
# in its source folder while it is made, and beside the executable once it
# ships. It also makes:
#   <target>_content   the content pack, <name>.kinpak beside the executable
#                      (with KIN_PACK_CONTENT; built with the game in shipping builds)
#   <target>_package   packages/<name>-<version>-<platform>.zip (.tar.gz on Linux):
#                      the executable, its content, and the license texts it must carry
# and install rules for the component <target>.

set(_KIN_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/..")

function(_kin_game_platform out_var)
    string(TOLOWER "${CMAKE_SYSTEM_NAME}" system)
    string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" processor)
    if(processor MATCHES "^(amd64|x86_64|x64)$")
        set(processor x86_64)
    elseif(processor MATCHES "^(arm64|aarch64)$")
        set(processor arm64)
    endif()
    set(${out_var} "${system}-${processor}" PARENT_SCOPE)
endfunction()

function(_kin_game_windows_resource target name title version icon)
    string(REGEX MATCHALL "[0-9]+" numbers "${version}")
    list(APPEND numbers 0 0 0 0)
    list(SUBLIST numbers 0 4 numbers)
    string(JOIN "," numeric ${numbers})
    set(icon_line "")
    if(icon)
        get_filename_component(icon "${icon}" ABSOLUTE)
        set(icon_line "1 ICON \"${icon}\"")
    endif()
    set(rc "${CMAKE_CURRENT_BINARY_DIR}/kin_game/${target}.rc")
    file(CONFIGURE OUTPUT "${rc}" CONTENT
"// Generated by kin_game; do not edit.
#include <winver.h>

${icon_line}

VS_VERSION_INFO VERSIONINFO
FILEVERSION ${numeric}
PRODUCTVERSION ${numeric}
FILEFLAGSMASK VS_FFI_FILEFLAGSMASK
FILEFLAGS 0
FILEOS VOS_NT_WINDOWS32
FILETYPE VFT_APP
FILESUBTYPE VFT2_UNKNOWN
BEGIN
    BLOCK \"StringFileInfo\"
    BEGIN
        BLOCK \"040904b0\"
        BEGIN
            VALUE \"FileDescription\", \"${title}\"
            VALUE \"FileVersion\", \"${version}\"
            VALUE \"InternalName\", \"${name}\"
            VALUE \"OriginalFilename\", \"${target}.exe\"
            VALUE \"ProductName\", \"${title}\"
            VALUE \"ProductVersion\", \"${version}\"
        END
    END
    BLOCK \"VarFileInfo\"
    BEGIN
        VALUE \"Translation\", 0x409, 1200
    END
END
")
    target_sources(${target} PRIVATE "${rc}")
endfunction()

function(kin_game target)
    cmake_parse_arguments(ARG "NO_CONTENT" "CONTENT;NAME;TITLE;VERSION;ICON" "FILES" ${ARGN})
    if(NOT ARG_NAME)
        set(ARG_NAME "${target}")
    endif()
    if(NOT ARG_CONTENT)
        set(ARG_CONTENT "${CMAKE_CURRENT_SOURCE_DIR}/content")
    endif()
    get_filename_component(content "${ARG_CONTENT}" ABSOLUTE)
    if(NOT ARG_TITLE)
        set(ARG_TITLE "${ARG_NAME}")
    endif()
    if(NOT ARG_VERSION)
        set(ARG_VERSION "${PROJECT_VERSION}")
    endif()
    if(NOT ARG_VERSION)
        set(ARG_VERSION "0.0.0")
    endif()

    kin_enable_release_optimizations(${target})
    kin_enable_release_link_optimizations(${target})

    target_compile_definitions(${target} PRIVATE KIN_GAME_CONTENT_NAME="${ARG_NAME}")
    if(ARG_NO_CONTENT)
        set(content "")
    elseif(NOT KIN_SHIPPING)
        target_compile_definitions(${target} PRIVATE KIN_GAME_CONTENT_DIR="${content}")
    endif()

    if(WIN32)
        _kin_game_windows_resource(${target} "${ARG_NAME}" "${ARG_TITLE}" "${ARG_VERSION}" "${ARG_ICON}")
        if(KIN_SHIPPING)
            # A windowed app: no console opens beside the game. Its log goes
            # with its saves instead (run_scene_app).
            set_target_properties(${target} PROPERTIES WIN32_EXECUTABLE ON)
            if(MSVC)
                target_link_options(${target} PRIVATE /ENTRY:mainCRTStartup) # keeps int main()
            endif()
        endif()
    endif()

    if(KIN_SHIPPING AND CMAKE_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        # The C++ runtime inside the game, so players need no newer libstdc++
        # than their system has. glibc stays shared: the build machine's
        # version is the oldest the game runs on (docs/shipping.md).
        target_link_options(${target} PRIVATE -static-libstdc++ -static-libgcc)
    endif()

    install(TARGETS ${target} RUNTIME DESTINATION . COMPONENT ${target})
    if(ARG_FILES)
        install(FILES ${ARG_FILES} DESTINATION . COMPONENT ${target})
    endif()
    install(FILES "${_KIN_ROOT_DIR}/LICENSE" DESTINATION licenses RENAME kin.txt COMPONENT ${target})
    install(FILES "${_KIN_ROOT_DIR}/docs/third_party_notices.md" DESTINATION licenses
            RENAME README.md COMPONENT ${target})
    foreach(license IN LISTS KIN_THIRD_PARTY_LICENSES)
        string(REPLACE "|" ";" license "${license}")
        list(GET license 0 license_name)
        list(GET license 1 license_file)
        install(FILES "${license_file}" DESTINATION licenses RENAME "${license_name}" COMPONENT ${target})
    endforeach()

    set(package_depends ${target})
    if(content AND IS_DIRECTORY "${content}")
        if(KIN_PACK_CONTENT)
            # kin_pack leaves an up-to-date pack alone, so this costs a scan of
            # the folder when nothing changed.
            set(pack "$<TARGET_FILE_DIR:${target}>/${ARG_NAME}.kinpak")
            add_custom_target(${target}_content
                COMMAND kin_pack create "${content}" "${pack}"
                COMMENT "Packing ${ARG_NAME} content"
                VERBATIM)
            if(KIN_SHIPPING)
                add_dependencies(${target} ${target}_content)
            endif()
            list(APPEND package_depends ${target}_content)
            install(FILES "${pack}" DESTINATION . COMPONENT ${target})
        else()
            install(DIRECTORY "${content}/" DESTINATION "${ARG_NAME}" COMPONENT ${target}
                    PATTERN ".*" EXCLUDE)
        endif()
    endif()

    _kin_game_platform(platform)
    set(package "${ARG_NAME}-${ARG_VERSION}-${platform}")
    set(packages "${CMAKE_BINARY_DIR}/packages")
    set(staging "${packages}/staging/${target}")
    if(WIN32)
        set(archive "${packages}/${package}.zip")
        set(tar_args cf "${archive}" --format=zip)
    else()
        set(archive "${packages}/${package}.tar.gz")
        set(tar_args czf "${archive}")
    endif()
    add_custom_target(${target}_package
        COMMAND "${CMAKE_COMMAND}" -E rm -rf "${staging}"
        COMMAND "${CMAKE_COMMAND}" --install "${CMAKE_BINARY_DIR}" --config $<CONFIG> --component ${target}
                --prefix "${staging}/${package}" --strip
        COMMAND "${CMAKE_COMMAND}" -E chdir "${staging}" "${CMAKE_COMMAND}" -E tar ${tar_args} "${package}"
        COMMAND "${CMAKE_COMMAND}" -E echo "Packaged ${archive}"
        COMMENT "Packaging ${ARG_NAME}"
        VERBATIM)
    add_dependencies(${target}_package ${package_depends})
endfunction()

# The older way to set up a game's assets, kept for games that use it: bakes
# KIN_ASSETS_ROOT into non-Release builds and, with KIN_COPY_GAME_ASSETS,
# copies the assets beside the binaries. It now also sets the game up with
# kin_game, its assets folder as the content.
function(kin_configure_game_assets target game_name)
    option(KIN_COPY_GAME_ASSETS "Copy game assets beside built binaries after build" OFF)

    set(options)
    set(one_value_args SOURCE_DIR)
    set(multi_value_args)
    cmake_parse_arguments(KIN_GAME "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

    if(NOT KIN_GAME_SOURCE_DIR)
        set(KIN_GAME_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/assets")
    endif()

    kin_game(${target} CONTENT "${KIN_GAME_SOURCE_DIR}" NAME "${game_name}")
    target_compile_definitions(${target} PRIVATE
        "$<$<NOT:$<CONFIG:Release>>:KIN_ASSETS_ROOT=\"${KIN_GAME_SOURCE_DIR}\">"
    )

    if(KIN_COPY_GAME_ASSETS)
        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E copy_directory
                "${KIN_GAME_SOURCE_DIR}"
                "$<TARGET_FILE_DIR:${target}>/assets/${game_name}"
            COMMENT "Copying ${game_name} assets"
        )
    endif()
endfunction()
